import React from "react";
import { CreditCard, ExternalLink, CheckCircle, Clock, PlayCircle, AlertCircle, Shield } from "lucide-react";

export default function RazorpayLivePanel({ actions, onSimulatePayment, isSimulating }) {
  const executedActions = (actions || []).filter((a) => a.status === "EXECUTED" || a.razorpay_link_id);

  return (
    <div className="bg-slate-850 rounded-2xl border border-slate-750 p-6 space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <CreditCard className="w-5 h-5 text-sky-400" />
            <span>Razorpay Test-Mode Execution Terminal</span>
          </h2>
          <p className="text-xs text-slate-400">
            Live payment links generated by the AI agent for approved growth campaigns
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-[11px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 px-2.5 py-1 rounded-full flex items-center gap-1.5">
            <Shield className="w-3 h-3" />
            <span>Strict Test Mode</span>
          </span>
        </div>
      </div>

      {/* Clearly labeled demo simulator banner */}
      <div className="bg-sky-950/30 border border-sky-500/30 rounded-xl p-3.5 flex items-start gap-3 text-xs">
        <AlertCircle className="w-4 h-4 text-sky-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <div className="font-bold text-sky-300">DEMO / TESTING UTILITY NOTICE</div>
          <p className="text-slate-300 text-[11px] leading-relaxed">
            You can click <strong className="text-white">"Open Checkout"</strong> to inspect the live Razorpay test checkout page,
            or click <strong className="text-sky-300">"Simulate Customer Payment"</strong> to trigger a test webhook that instantly updates
            the merchant's revenue goal, updates the customer's repeat-purchase RFM segment, and records an immutable audit log entry.
          </p>
        </div>
      </div>

      {executedActions.length === 0 ? (
        <div className="text-center py-8 border border-dashed border-slate-750 rounded-xl">
          <p className="text-xs text-slate-400">
            No Razorpay test payment links executed yet. Review and approve opportunities above to generate live test links.
          </p>
        </div>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-slate-900/80 text-slate-400 uppercase tracking-wider text-[10px] border-b border-slate-750">
              <tr>
                <th className="py-3 px-4">Link ID</th>
                <th className="py-3 px-4">Target Customer</th>
                <th className="py-3 px-4">Amount</th>
                <th className="py-3 px-4">Offer Discount</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4">Razorpay Test URL</th>
                <th className="py-3 px-4 text-right">Hackathon Testing Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800">
              {executedActions.map((act) => {
                const isPaid = act.payment_status === "PAID";

                return (
                  <tr key={act.id} className="hover:bg-slate-800/40 transition">
                    <td className="py-3.5 px-4 font-mono text-sky-400 font-semibold">{act.razorpay_link_id}</td>
                    <td className="py-3.5 px-4 font-medium text-white">{act.target_customer_name || "Target VIP"}</td>
                    <td className="py-3.5 px-4 font-bold text-white">
                      ₹{act.final_price?.toLocaleString("en-IN", { minimumFractionDigits: 2 })}
                    </td>
                    <td className="py-3.5 px-4 text-amber-400 font-semibold">{act.proposed_discount_pct}% Off</td>
                    <td className="py-3.5 px-4">
                      {isPaid ? (
                        <span className="inline-flex items-center gap-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded-full text-[11px] font-bold">
                          <CheckCircle className="w-3 h-3" />
                          PAID
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 bg-amber-500/10 text-amber-400 border border-amber-500/30 px-2 py-0.5 rounded-full text-[11px] font-bold">
                          <Clock className="w-3 h-3" />
                          PENDING
                        </span>
                      )}
                    </td>
                    <td className="py-3.5 px-4">
                      {act.razorpay_short_url ? (
                        <a
                          href={act.razorpay_short_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="inline-flex items-center gap-1 text-sky-400 hover:text-sky-300 font-medium hover:underline"
                        >
                          <span>Open Checkout</span>
                          <ExternalLink className="w-3 h-3" />
                        </a>
                      ) : (
                        <span className="text-slate-500">—</span>
                      )}
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      {isPaid ? (
                        <span className="text-[11px] text-emerald-400 font-medium">
                          {act.is_simulated ? "Simulated Payment Recorded" : "Captured via Webhook"}
                        </span>
                      ) : (
                        <button
                          onClick={() => onSimulatePayment(act.id)}
                          disabled={isSimulating}
                          title="Simulate customer payment completion for live demo evaluation"
                          className="inline-flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-500 text-slate-950 font-bold px-3 py-1.5 rounded-lg text-xs transition shadow-md shadow-emerald-600/20 disabled:opacity-50 cursor-pointer"
                        >
                          <PlayCircle className="w-3.5 h-3.5" />
                          <span>Simulate Payment</span>
                        </button>
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
